### PR TITLE
Add initial CWT support

### PR DESCRIPTION
**Pull request by daviddrysdale**

### CODE REVIEW

**Comment by falko17** [comment]
Hi! We are currently working on implementing a Rust library for the [ACE-OAuth](https://www.ietf.org/archive/id/draft-ietf-ace-oauth-authz-46.html) standard, for which we are using coset. 
CWTs are an essential part of this standard — I was wondering whether there is anything still missing (apart from a rebase on `main`) until this branch is ready to merge? If there's anything that has yet to be implemented, I'd of course be willing to help out as well. Thank you.

**Comment by daviddrysdale** [comment]
>  I was wondering whether there is anything still missing (apart from a rebase on `main`)

I've done the rebase, but I suspect there are things still missing &ndash;this was just an initial sketch of the basic `ClaimsSet` type.

On a quick skim of the [RFC](https://datatracker.ietf.org/doc/html/rfc8392) I'd imagine that it would be nice to improve integration with the rest of the crate, so that some of the steps in [7.2](https://datatracker.ietf.org/doc/html/rfc8392#section-7.2) were handled. However, that's probably going to need a wrapper around `ClaimsSet` that also preserves any original serialized data, so ordering issues don't affect signatures and the like (cf. #29).  Tags and nested claims also look like they could do with some helper code.

However, I'm not currently using CWT so I don't have a great sense of what's really needed.  Any thoughts?

**Comment by daviddrysdale** [comment]
The basics that are already here do allow some level of functionality though &ndash; added an [example](https://github.com/google/coset/pull/11/files#diff-041818e4920e6b60a9c0214496fc082edd25195202de95017572ceca8149e24f)

**Comment by falko17** [comment]
Thanks for your quick reply and the example! While some additional functionality like the wrapper around `ClaimsSet` you mentioned would indeed be nice, what's already here (i.e. the basic `ClaimsSet` type) works well already for now — depending on how this project is organized and how much time you think implementing this helper code will take, maybe a compromise would be merging the PR as is and handling additions like the wrapper in a follow-up PR?

**Review by ciphergoth — APPROVED** [review]

**Comment by daviddrysdale** [comment]
> do you think it's possible to release a new version of coset on crates.io?

[Done](https://crates.io/crates/coset/0.3.2)

**Pull request merged**
